sites:
  - name: "PokeRogue"
    sitemap_urls:
      - "https://pokerogue.io/sitemap.xml"
    active: true
  - name: "Wordle2"
    sitemap_urls:
      - "https://wordle2.io/sitemap.xml"
    active: true
  - name: "1Games"
    sitemap_urls:
      - "https://1games.io/sitemap.xml"
    active: true
  - name: "AZGames"
    sitemap_urls:
      - "https://azgames.io/sitemap.xml"
    active: true
  - name: "CookieClicker2"
    sitemap_urls:
      - "https://cookie-clicker2.com/sitemap.xml"
    active: true
  - name: "Phrazle"
    sitemap_urls:
      - "https://phrazle.io/sitemap.xml"
    active: true
  - name: "Sprunki"
    sitemap_urls:
      - "https://sprunki.org/sitemap.xml"
    active: true
  - name: "ThatsNotMyNeighbor"
    sitemap_urls:
      - "https://thatsnot-myneighbor.io/sitemap.xml"
    active: true
  - name: "GeometryDashWave"
    sitemap_urls:
      - "https://geometrydashwave.io/sitemap.xml"
    active: true
  - name: "SmashyRoad"
    sitemap_urls:
      - "https://smashy-road.io/sitemap.xml"
    active: true
  - name: "GeometryDashIO"
    sitemap_urls:
      - "https://geometrylite.io/sitemap.xml"
    active: true
  - name: "Bloxinformer"
    sitemap_urls:
      - "https://bloxinformer.com/sitemap.xml"
    active: true
  - name: "Pollo"
    sitemap_urls:
      - "https://pollo.ai/sitemap.xml"
    active: true
  - name: "Bylo"
    sitemap_urls:
      - "https://bylo.ai/sitemap-secondary-page-0.xml"
    active: true


feishu:
  webhook_url: "https://open.larksuite.com/open-apis/bot/v2/hook/c78e401d-1a1f-4500-830b-36528b83011a"
  secret: "YOUR_SECRET"

storage:
  retention_days: 7
  data_dir: "./data"