sites:
  - name: "SpotleGame"
    sitemap_urls:
      - "https://spotlegame.com/sitemap.xml"
    active: true
- name: "PokeRogue"
    sitemap_urls:
      - "https://pokerogue.io/sitemap.xml"
    active: true
  - name: "Wordle2"
    sitemap_urls:
      - "https://wordle2.io/sitemap.xml"
    active: true
  - name: "1Games"
    sitemap_urls:
      - "https://1games.io/sitemap.xml"
    active: true
  - name: "AZGames"
    sitemap_urls:
      - "https://azgames.io/sitemap.xml"
    active: true
- name: "CookieClicker2"
    sitemap_urls:
      - "https://cookie-clicker2.com/sitemap.xml"
    active: true
  - name: "Phrazle"
    sitemap_urls:
      - "https://phrazle.io/sitemap.xml"
    active: true
  - name: "Sprunki"
    sitemap_urls:
      - "https://sprunki.org/sitemap.xml"
    active: true
  - name: "ThatsNotMyNeighbor"
    sitemap_urls:
      - "https://thatsnot-myneighbor.io/sitemap.xml"
    active: true
  - name: "EscapeRoad"
    sitemap_urls:
      - "https://escaperoad.io/sitemap.xml"
    active: true
  - name: "TapRoad"
    sitemap_urls:
      - "https://taproad.io/sitemap.xml"
    active: true
  - name: "GeometryDashWave"
    sitemap_urls:
      - "https://geometrydashwave.io/sitemap.xml"
    active: true
  - name: "LevelDevil2"
    sitemap_urls:
      - "https://leveldevil2.io/sitemap.xml"
    active: true

feishu:
  webhook_url: "https://open.feishu.cn/open-apis/bot/v2/hook/c84594b9-e8dd-4828-a24d-cb1175f41f3a"
  secret: "YOUR_SECRET"

storage:
  retention_days: 7
  data_dir: "./data"
