sites:
  - name: "pollo"
    sitemap_urls:
      - "https://pollo.ai/sitemap.xml"
    active: true
  - name: "fotor"
    sitemap_urls:
      - "https://www.fotor.com/sitemaps/v2/index.xml"
    active: true


feishu:
  webhook_url: ""
  secret: "YOUR_SECRET"

storage:
  retention_days: 7
  data_dir: "./data"
